server:
  port: 8010
spring:
  application:
    name: server-provider
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defauleZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
