server:
  port: 8050
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defauleZone: http://127.0.0.1:8761/eureka/

#给服务提供者 server-provider 提供映射
zuul:
  routes:
    server-provider: /p/**