server:
  port: 8040
spring:
  application:
    name: consumer-feign

eureka:
  client:
    service-url:
      defauleZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1

feign:
  hystrix:
    enabled: true
logging:
  level:
    cn.wengzi.external: debug
