server:
  port: 8060

spring:
  application:
    name: hystrix
eureka:
  client:
    service-url:
      defauleZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
